name: Scheduled execution
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Newman
        run: npm install -g newman
      - name: Run Gmail Collection
        env:
          GMAIL_SECRET_EMAIL: ${{ secrets.GMAIL_USER_EMAIL }}
          GMAIL_SECRET_TOKEN: ${{ secrets.GMAIL_TOKEN }}
        run: |
          newman run collection.json \
          -e environment.json \
          --env-var "client_email=$GMAIL_SECRET_EMAIL" \
          --env-var "access_token=$GMAIL_SECRET_TOKEN"
