name: Scheduled execution
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Newman
        run: npm install -g newman
      - name: Run Gmail Collection
        run: |
          newman run collection.json \
          -e environment.json \
          --env-var "access_token=${{ secrets.GMAIL_TOKEN }}"
          --env-var "client_email=${{ secrets.GMAIL_USER_EMAIL }}"


      - name: Debug Secret Availability
        run: |
          if [ -z "${{ secrets.GMAIL_USER_EMAIL }}" ]; then
            echo "ERROR: GMAIL_USER_EMAIL is EMPTY"
          else
            echo "SUCCESS: GMAIL_USER_EMAIL is found"
          fi
